# Generated by Django 5.2.7 on 2025-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='location_type',
        ),
        migrations.AddField(
            model_name='address',
            name='Address_type',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10, null=True),
        ),
    ]
