# Generated by Django 5.2.7 on 2025-11-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image_alter_product_seller'),
        ('users', '0003_remove_address_location_type_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.userprofile'),
            preserve_default=False,
        ),
    ]
