# Generated by Django 5.2.7 on 2025-11-29 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_description_alter_product_seller'),
        ('users', '0003_remove_address_location_type_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.userprofile'),
            preserve_default=False,
        ),
    ]
